### ISSUE TITLE
 Autoware.universe  for carla simulator

### ISSUE THREAD

**Issue by liuypcoding** [youxiho1/autoware.universe-carla-ros-bridge#1]
It's great! The  Bridge support Autoware.universe  for carla simulator? Thanks!

**Comment by youxiho1** [comment]
Yep, I'm working on it

**Comment by youxiho1** [comment]
There still remains lots of problems, hope I can finish it soon...

**Comment by youxiho1** [comment]
> It's great! The Bridge support Autoware.universe for carla simulator? Thanks!
Yep, I'm working on it.
There still remains lots of problems, hope I can finish it soon...

**Comment by youxiho1** [comment]
> It's great! The Bridge support Autoware.universe for carla simulator? Thanks!

Yep, but I'm still working on it.
There still remains lots of problems, hope I can finish it soon...

**Comment by liuypcoding** [comment]
> > It's great! The Bridge support Autoware.universe for carla simulator? Thanks!
> 
> Yep, but I'm still working on it. There still remains lots of problems, hope I can finish it soon...

It's a video show  carla bridge with Autoware.universe , hope a litte helpful  . Looking forward to your ros-bridge ！

[https://www.youtube.com/watch?v=u9QmeRCX2rA](url)

**Comment by youxiho1** [comment]
> > > It's great! The Bridge support Autoware.universe for carla simulator? Thanks!
> > 
> > 
> > Yep, but I'm still working on it. There still remains lots of problems, hope I can finish it soon...
> 
> It's a video show carla bridge with Autoware.universe , hope a litte helpful . Looking forward to your ros-bridge ！
> 
> [https://www.youtube.com/watch?v=u9QmeRCX2rA](url)

Thx, I'm making every effort to implement this ros-bridge.
Ah, I've seen this video before. And you can find his repo at https://github.com/hatem-darweesh/op_bridge/tree/ros2
If you only want to use the planning module, you might try that repo~

**Comment by liuypcoding** [comment]
> > > > It's great! The Bridge support Autoware.universe for carla simulator? Thanks!
> > > 
> > > 
> > > Yep, but I'm still working on it. There still remains lots of problems, hope I can finish it soon...
> > 
> > 
> > It's a video show carla bridge with Autoware.universe , hope a litte helpful . Looking forward to your ros-bridge ！
> > [https://www.youtube.com/watch?v=u9QmeRCX2rA](url)
> 
> Thx, I'm making every effort to implement this ros-bridge. Ah, I've seen this video before. And you can find his repo at https://github.com/hatem-darweesh/op_bridge/tree/ros2 If you only want to use the planning module, you might try that repo~

Hi! The author you sent is adapted carla and autoware.universe:
[CARLA Simulator + Autoware Universe Tutorials](https://github.com/autowarefoundation/autoware/discussions/2828)
[autoware.universe tutorial](https://www.youtube.com/watch?v=dxwwNacez7o)

Hope it helps you, thank you! !
